/**
 * PG Rental Agreement Document Structure
 * Modify this file to change the Agreement document layout and content
 */

export const agreementDocumentStructure = {
  // Document metadata
  metadata: {
    title: (userName) => `PG Rental Agreement - ${userName}`,
    author: "PG Management System",
    subject: "PG Rental Agreement - Digitally Signed",
  },

  // Header configuration
  header: {
    height: 80,
    backgroundColor: "#6366f1",
    title: {
      text: "PG RENTAL AGREEMENT",
      fontSize: 20,
      color: "#ffffff",
      font: "Helvetica-Bold",
      y: 30,
    },
    subtitle: {
      text: "Digitally Signed Agreement",
      fontSize: 10,
      color: "rgba(255, 255, 255, 0.9)",
      font: "Helvetica",
      y: 60,
    },
  },

  // Colors used throughout the document
  colors: {
    primary: "#0f172a",
    accent: "#6366f1",
    lightGray: "#f8fafc",
    border: "#e2e8f0",
    textSecondary: "#64748b",
    success: "#10b981",
  },

  // Sections configuration
  sections: {
    parties: {
      title: "PARTIES",
      fontSize: 12,
      font: "Helvetica-Bold",
      ownerLabel: "OWNER (Lessor):",
      tenantLabel: "TENANT (Lessee):",
      fields: ["name", "email", "phone"],
    },
    propertyDetails: {
      title: "PROPERTY DETAILS",
      fontSize: 12,
      font: "Helvetica-Bold",
      fields: [
        { key: "propertyName", label: "Property Name" },
        { key: "address", label: "Address" },
        { key: "roomNumber", label: "Room Number" },
        { key: "bedNumber", label: "Bed Number" },
      ],
    },
    financialTerms: {
      title: "FINANCIAL TERMS",
      fontSize: 12,
      font: "Helvetica-Bold",
      fields: [
        { key: "monthlyRent", label: "Monthly Rent", format: "currency" },
        {
          key: "securityDeposit",
          label: "Security Deposit",
          format: "currency",
        },
        { key: "moveInDate", label: "Move-in Date", format: "date" },
        { key: "rentDueDate", label: "Rent Due Date", format: "text" },
        {
          key: "lastPenaltyFreeDate",
          label: "Last Penalty-Free Date",
          format: "text",
        },
        { key: "lateFee", label: "Late Fee", format: "text" },
        { key: "noticePeriod", label: "Notice Period", format: "text" },
        { key: "lockInPeriod", label: "Lock-in Period", format: "text" },
      ],
    },
    facilities: {
      title: "FACILITIES INCLUDED",
      fontSize: 12,
      font: "Helvetica-Bold",
    },
    houseRules: {
      title: "HOUSE RULES",
      fontSize: 12,
      font: "Helvetica-Bold",
      defaultText:
        "Standard house rules apply. Please maintain cleanliness and respect other tenants.",
    },
    consent: {
      title: "CONSENT & VERIFICATION",
      fontSize: 12,
      font: "Helvetica-Bold",
      items: [
        "✓ All personal details provided are correct and verified through digital eKYC",
        "✓ The Tenant has reviewed all PG details and agrees to the terms",
        "✓ The Tenant authorizes the PG to verify identity using digital eKYC",
        "✓ The Tenant agrees to abide by the PG Agreement & House Rules",
      ],
      statement:
        "This agreement is accepted digitally by the Tenant through secure OTP verification.",
    },
    signatures: {
      title: "DIGITAL SIGNATURES",
      fontSize: 12,
      font: "Helvetica-Bold",
      boxHeight: 80,
      ownerLabel: "OWNER",
      tenantLabel: "TENANT (E-SIGNED)",
    },
  },

  // Footer configuration
  footer: {
    lines: [
      "This is a digitally signed agreement. Generated on {date}",
      "Generated by PG Management System - Streamivus",
    ],
    fontSize: 8,
    color: "#64748b",
    font: "Helvetica",
  },

  // Formatting functions
  formatters: {
    date: (date) => {
      if (!date) return "N/A";
      const d = new Date(date);
      return d.toLocaleDateString("en-IN", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
    },
    currency: (amount) => {
      if (amount == null || isNaN(amount)) return "Rs. 0";
      return `Rs. ${Number(amount).toLocaleString("en-IN")}`;
    },
    ordinalSuffix: (n) => {
      const j = n % 10;
      const k = n % 100;
      if (j === 1 && k !== 11) return "st";
      if (j === 2 && k !== 12) return "nd";
      if (j === 3 && k !== 13) return "rd";
      return "th";
    },
  },
};
