export const FACILITY_OPTIONS = [
  "AC",
  "NON_AC",
  "WIFI",
  "FOOD",
  "LAUNDRY",
  "HOUSEKEEPING",
  "PARKING",
  "CCTV",
  "POWER_BACKUP",
  "GEYSER",
  "RO_WATER",
  "FRIDGE",
  "WASHING_MACHINE",
  "ATTACHED_BATHROOM",
  "FURNISHED",
];

export const GENDER_OPTIONS = ["BOYS", "GIRLS", "COED"];
