/**
 * eKYC Document Structure
 * Modify this file to change the eKYC document layout and content
 */

export const ekycDocumentStructure = {
  // Document metadata
  metadata: {
    title: (userName) => `eKYC Document - ${userName}`,
    author: "PG Management System",
    subject: "Tenant eKYC Verification Document",
  },

  // Header configuration
  header: {
    height: 80,
    backgroundColor: "#6366f1",
    title: {
      text: "eKYC VERIFICATION DOCUMENT",
      fontSize: 24,
      color: "#ffffff",
      font: "Helvetica-Bold",
      y: 30,
    },
    subtitle: {
      text: "Digital Identity Verification",
      fontSize: 10,
      color: "rgba(255, 255, 255, 0.9)",
      font: "Helvetica",
      y: 60,
    },
  },

  // Colors used throughout the document
  colors: {
    primary: "#0f172a",
    accent: "#6366f1",
    lightGray: "#f8fafc",
    border: "#e2e8f0",
    textSecondary: "#64748b",
    success: "#10b981",
  },

  // Sections configuration
  sections: {
    verificationStatus: {
      title: "VERIFICATION STATUS",
      fontSize: 12,
      font: "Helvetica-Bold",
      boxHeight: 40,
      verifiedText: "✓ VERIFIED",
      verifiedFontSize: 14,
      verifiedColor: "#10b981",
    },
    personalDetails: {
      title: "PERSONAL DETAILS",
      fontSize: 12,
      font: "Helvetica-Bold",
      fields: [
        { key: "fullName", label: "Full Name" },
        { key: "dateOfBirth", label: "Date of Birth" },
        { key: "gender", label: "Gender" },
        { key: "fatherMotherName", label: "Father/Mother Name" },
        { key: "phone", label: "Phone" },
        { key: "email", label: "Email" },
        { key: "permanentAddress", label: "Permanent Address" },
        { key: "occupation", label: "Occupation" },
        { key: "companyCollegeName", label: "Company/College Name" },
      ],
    },
    idDetails: {
      title: "IDENTITY DOCUMENT DETAILS",
      fontSize: 12,
      font: "Helvetica-Bold",
      fields: [
        { key: "idType", label: "ID Type" },
        { key: "idNumber", label: "ID Number" },
      ],
    },
    verificationTimestamp: {
      title: "VERIFICATION TIMESTAMP",
      fontSize: 12,
      font: "Helvetica-Bold",
    },
  },

  // Footer configuration
  footer: {
    lines: [
      "This is a digitally generated eKYC verification document.",
      "Generated by PG Management System - Streamivus",
    ],
    fontSize: 8,
    color: "#64748b",
    font: "Helvetica",
  },

  // Field formatting functions
  formatters: {
    date: (date) => {
      if (!date) return "N/A";
      const d = new Date(date);
      return d.toLocaleDateString("en-IN", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
    },
  },
};
